import chalk from 'chalk';
import { print } from '../ui.js';

const commands = [
  { name: 'init',    desc: 'Set up gitwrite in the current directory'                    },
  { name: '',        desc: chalk.dim('(First run also configures your global defaults)') },
  { name: 'start',   desc: 'Start watching your registered directories'                  },
  { name: 'stop',    desc: 'Stop the daemon gracefully'                                  },
  { name: 'restart', desc: 'Stop and restart  (useful after config changes)'             },
  { name: '',        desc: ''                                                             },
  { name: 'status',  desc: 'Show what gitwrite is watching and what it\'s done lately'   },
  { name: 'logs',    desc: 'Tail the activity log'                                       },
  { name: '',        desc: ''                                                             },
  { name: 'config',  desc: 'Edit your global defaults or local directory overrides'      },
  { name: 'add',     desc: 'Add a directory to your watch list'                          },
  { name: 'remove',  desc: 'Remove a directory from your watch list'                     },
  { name: '',        desc: ''                                                             },
  { name: 'help',    desc: 'List all available commands'                                 },
];

const tips = [
  'Run gitwrite init in any directory to register it.',
  'Run gitwrite config from inside a watched directory to set local overrides.',
  'gitwrite commits to whatever branch you\'re on — switch branches freely.',
  'Branch mode "autogenerated" names your session branch automatically.',
  'gitwrite requires a configured Git remote to push your work offsite.',
];

export function help() {
  print.gap();
  print.brand('gitwrite — Private, versioned writing for people who live in the terminal.');
  print.gap();

  console.log(chalk.dim('  commands'));
  print.gap();

  for (const { name, desc } of commands) {
    const k = chalk.white(name.padEnd(12));
    console.log(`    ${k}${desc}`);
  }

  print.gap();
  console.log(chalk.dim('  tips'));
  print.gap();

  for (const tip of tips) {
    print.hint(`· ${tip}`);
  }

  print.gap();
  console.log(chalk.dim('  docs + source    github.com/TBiddy/gitwrite'));
  print.gap();
}
